### ISSUE TITLE
Is the Github Container Registry already supported?

### ISSUE THREAD

**Issue by dersmon** [acdh-oeaw/vocabseditor#57]
The main README does not mention the [registry](https://github.com/acdh-oeaw/vocabseditor/pkgs/container/vocabseditor). And when trying to pull and run the latest image I get the following error:

```
vocabs-editor         | Traceback (most recent call last):
vocabs-editor         |   File "manage.py", line 22, in <module>
vocabs-editor         |     execute_from_command_line(sys.argv)
vocabs-editor         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
vocabs-editor         |     utility.execute()
vocabs-editor         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
vocabs-editor         |     django.setup()
vocabs-editor         |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
vocabs-editor         |     apps.populate(settings.INSTALLED_APPS)
vocabs-editor         |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
vocabs-editor         |     app_config = AppConfig.create(entry)
vocabs-editor         |   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
vocabs-editor         |     import_module(entry)
vocabs-editor         |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
vocabs-editor         |     return _bootstrap._gcd_import(name[level:], package, level)
vocabs-editor         |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
vocabs-editor         |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
vocabs-editor         |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
vocabs-editor         | ModuleNotFoundError: No module named 'django_extensions'
```

**Comment by csae8092** [comment]
Thanks for pointing this out. I'll into this next week

**Comment by csae8092** [comment]
I guess the error is related with running the application in DEBUG mode, see https://github.com/acdh-oeaw/vocabseditor/blob/master/vocabseditor/settings.py#L67

I'll add `django_extensions` to the requirements.txt (also used by docker) so this shouldn't be an issue any more
